### ISSUE TITLE
[Question] Echo Time Limit?

### ISSUE THREAD

**Issue by volkflo** [Ealenn/Echo-Server#55]
Just a little question:
https://github.com/Ealenn/Echo-Server/blob/cb68b934da0c43b3f0d979622a1ca20fe6f91556/src/middlewares/customResponseTime.js#L3-L9
Why is there a limit of `30000`?

**Comment by Ealenn** [comment]
Hi @volkflo !
Technically, nothing force this limit.
It’s just, security, for no-blocking main thread. 🤐

I must add this limit to the configuration to be more flexible. It's not the first time that it blocks someone.

You can find a fork with no limit if you want 🤭 And I will keep this issue open for futur Pull Request 😉

**Comment by Rauno56** [comment]
Interesting... Could you elaborate on that, please?
`setTimeout` doesn't block (the main thread). And security-wise?

**Comment by Ealenn** [comment]
I am not very familiar with single-threaded Javascript logic 😕Because JavaScript doesn’t really have multi-threading capabilities..

Just, I think it's possible to slow down the system by multiplying the `setTimeout` function.
In the case of _(public/open)_ commissioning of this project, I prefer put a limit or block requests to prevent a denial of service with this endpoint.

To prevent drifts, I placed it arbitrarily at 30 seconds. 
> Because an web request is not supposed to be longer than 30 seconds... **(It's debatable, I agree 👼 )**

Do you understand or... Just have no reason for that ? 
It's possible, I could be wrong 😆

**Comment by Rauno56** [comment]
I guess it serves as a double safety net in a way. However, I personally don't see it being necessary since

1. the max timeout could be configured from the server-side instead, just like your PR already does;
2. I see an echo server rarely used in a situation where it's realistically exploitable via DOS attack - it's more of a debugging tool.

Accumulating pending requests could definitely be a problem, but it is just as big with the timeout limit set to 30s as it is when it's 10s or 1000s.

I think #57 is an adequate solution! Thanks, @Ealenn!

**Comment by Ealenn** [comment]
Thank's for this feedback @Rauno56 

What do you think about set by default 1 minute and leaving the responsibility for this configuration in case of public deployment?

You should also know, I would like to add a socket system to view in live the requests. This will probably be deployed via Heroku on a "Free dyno instance". This is the reason for this "protection".

**Comment by Rauno56** [comment]
You are suggesting making the default of max timeout 1 minute and keeping it configurable via options mentioned https://github.com/Ealenn/Echo-Server/issues/55#issuecomment-756661674? Yes, that's what I'd support as well!

Socket system? To me, it sounds exactly what the logs are for. Depends on where you want to take the project, but I'd personally keep the application as small and concise as possible.

When I was looking for an application to debug my k8s ingress setup, I chose this one because I could scan through all of the code in a minute and be sure it's not doing anything funny - sockets would look unconventional and "funny" to me in an application like that, especially if the reasoning is to see logs.

**Comment by Ealenn** [comment]
I also use it to debug my gateways on Kubernetes or Docker-Compose (especially the transformation with Traefik or Kong)

I will **improve the logs first** (to get all the information) and be able to integrate them into Seq or an ELK.
You're right to keep the app as small as possible, that was the mentality of the project 👍

Thank you for everything
