### ISSUE TITLE
[BUG] Fatal process OOM in insufficient memory to create an Isolate

### ISSUE THREAD

**Issue by drusin** [Ealenn/Echo-Server#74]
**Describe the bug**
When trying to run the Echo server it crashes immediately with this output:
```

<--- Last few GCs --->


<--- JS stacktrace --->


#
# Fatal process OOM in insufficient memory to create an Isolate
#

```

**To Reproduce**
I am running a free oracle cloud linux/arm64/v8 instance with 1 cpu core and 6GB of memory. I have docker and k3s installed. I am using the command `docker run -p 3000:80 ealen/echo-server`

**Expected behavior**
The container doesn't crash with an OOM error

**Additional context**
You can create a free oracle cloud account and create the v8 vm there for free.

**Comment by Ealenn** [comment]
Hi @drusin !

I'm sorry... I can't reproduce on my arm64/v8 personal instance :( 

How do you start the server? 
You can use the chart available here for ease of use (don't forget to change the tag to 0.5.1) 
https://artifacthub.io/packages/helm/ealenn/echo-server

Can you check if this problem is related to the echo-server or an external cause ? 
Probably a lack of RAM memory or full disk access.

I would like to help you. I think the error is caused by your instance.

- Your K3S nodes have sufficient resources to operate ?
- Your instances disk have sufficient IO ?
